In [2]:
using HTTP, JSON, PrettyTables, JLD, DotEnv, Distributions, LinearAlgebra, Dates, MySQL

In [3]:
cfg = DotEnv.config("../.env")
files_path = cfg["files_path"]
adjacency = load(files_path*"placement_rates.jld")["placement_rates"]
sinks = load(files_path*"sinks.jld")["sinks"]
classification_properties = load(files_path*"classification_properties.jld")["classification_properties"]
refresh_mysql_db = false
classification_properties
institution_counts = load(files_path*"/institution_counts.jld", "institution_counts");

11-element Vector{Any}:
  24
  77
 198
 345
 621
 226
 335
 801
 614
 674
 814

In [24]:
classification_properties

Dict{String, Any} with 7 entries:
  "data_loaded"      => DateTime("2025-07-22T03:35:38.437")
  "number_of_types"  => 5
  "labels"           => Any["Public Sector", "Private Sector", "Postdocs", "Lec…
  "number_of_sinks"  => 6
  "algorithm_run_id" => 7
  "sink_alloc"       => Any[6, 6, 6, 6, 6, 6, 6, 6, 6, 6  …  11, 11, 11, 11, 11…
  "counter"          => Any[226, 335, 801, 614, 674, 814]

In [37]:
adjacency

11×5 Matrix{Int32}:
 1638   525   300   62   16
 1444  1587   566  165   38
 1137  1486  1402  221   73
  375   692   623  682  104
   36    77   107   92  460
  716   678   396  108   55
  926   549   349   99   54
  161   237   219   84   66
   65   107   163   82  107
  319   302   192   62   58
  250   355   422  168  168

In [40]:
adjacency[12]

525

# Likelihood Ratios

The objective is to calculate the probability of each individual university's profiles of hires and placements given the placement rates estimated for each of the tiers in the classification.  The probabilities are then compared across tiers by calculating the ratio of each of these probabilities to the probability they have given the tier in which the university was placed by the classification algorithm.  If a university is classified as tier 1, then the probabililty of its hires and placements should he bigher using the rates estimated for tier 1 than they are using the rates estimated for tier 2.

We'll actually do it for hires and placements separately as well to check how restrictive is the assumption that universities who are the best at placing students are also best at hiring them.


In [4]:
hiring_rates = zeros(size(adjacency)[1], size(adjacency)[2]);
for i in 1:size(adjacency)[1], j in 1:size(adjacency)[2]
    hiring_rates[i,j] = 
    adjacency[i,j]/institution_counts[i]
end
placement_rates = zeros(size(adjacency)[1], size(adjacency)[2]);
for i in 1:size(adjacency)[1], j in 1:size(adjacency)[2]
    placement_rates[i,j] = 
    adjacency[i,j]/institution_counts[j]
end

The next task is to load the academic placements and the tier information

In [5]:
#academic_builder = load(files_path*"academic_builder.jld")["academic_builder"];
filtered_data = load(files_path*"filtered_data.jld")["filtered_data"];
#institutions = load(files_path*"institutions.jld")["institutions"]
#out = load(files_path*"out.jld")["out"];



In [7]:
id_to_type_api = JSON.parsefile(files_path*"id_to_type_api.json");

In [8]:
function hiring_outcomes(filtered_data, id_to_type_api, num_types, ejm_id)
    cnt = zeros(Int64,num_types)
    #println("ejm_is is ",typeof(ejm_id), "\n")
    for placement in filtered_data
        if placement["to_institution_id"] ==  ejm_id
            #println(placement["from_institution_id"], " has type ", typeof(placement["from_institution_id"]))
            t = type_lookup(id_to_type_api,placement["from_institution_id"])
            #hack because from_institution_id = 1021 return nulls (Tech University of Brauschweig)
            # and this is the only missing id 1021 is type 5
            if t == 0 
                t = 5
            end
            #println(placement["from_institution_id"], " returns ", t, " which has type ",typeof(t))
            cnt[t] += 1
        end
    end
    return cnt
end

function placement_outcomes(filtered_data, sinks, id_to_type_api, num_types, ejm_id)
    cnt = zeros(Int64, num_types)
    for placement in filtered_data
        if placement["from_institution_id"] ==  string(ejm_id) || placement["from_institution_id"] ==  ejm_id
            #println(placement["to_name"])
            k = placement["to_institution_id"]
            t = type_lookup(id_to_type_api,string(k))
            #println(placement["from_institution_id"], " returns ", t, " which has type ",typeof(t))
            if t > 0
                cnt[t] += 1
            else
                p = placement["to_name"]
                #println("checking ", p)
                n = 1
                for sink in sinks
                    if p in sink
                        cnt[5+n] += 1 
                        break 
                    else
                        n += 1
                    end
                end
            end
        end
    end
    return cnt
end

function type_lookup(id_to_type_api, ejm_id)
    for x in id_to_type_api
        if x["institution_id"] == ejm_id
            return x["type"]
        end
    end
    return 0
end

function to_type_lookup(id_to_type_api, ejm_id)
    for x in id_to_type_api
        if x["institution_id"] == string(ejm_id)
            return x["type"]
        end
    end
    return 0
end

function name_lookup(id_to_type_api, ejm_id)
    for x in id_to_type_api
        if x["institution_id"] == string(ejm_id)
            return x["name"]
        end
    end
end

function institution_lookup(id_to_type_api, ejm_id)
    for x in id_to_type_api
        if x["institution_id"] == string(ejm_id)
            return x
        end
    end
end        

institution_lookup (generic function with 1 method)

In [14]:
all_data = load(files_path*"current_estimates.jld")

Dict{String, Any} with 1 entry:
  "s" => [0.749139, 0.748506, 0.972897, 0.678316, 1.01335, 4.1912, 3.70251, 2.6…

In [19]:
all_data["s"][1]

0.7491391725144698

In [20]:

expected_offers = load(files_path*"expected_offers.jld")["expected_offers"]
offer_values = []
for j in 1:length(expected_offers)
    push!(offer_values, expected_offers[j])
end
tier_values = []
for j in 1:5
    push!(tier_values, all_data["s"][j])
end

In [26]:
names = []

for i in 1:classification_properties["number_of_types"] + classification_properties["number_of_sinks"]
    if i <= classification_properties["number_of_types"]
        push!(names,string("TIER", i, " (", institution_counts[i]," insts)"))
    else
        push!(names, string(classification_properties["labels"][i-classification_properties["number_of_types"]], 
                " (", institution_counts[i]," insts)"))
    end
#counter\
end
names

11-element Vector{Any}:
 "TIER1 (24 insts)"
 "TIER2 (77 insts)"
 "TIER3 (198 insts)"
 "TIER4 (345 insts)"
 "TIER5 (621 insts)"
 "Public Sector (226 insts)"
 "Private Sector (335 insts)"
 "Postdocs (801 insts)"
 "Lecturers (614 insts)"
 "Other Groups (674 insts)"
 "Teaching Universities (814 insts)"

In [27]:
h = ["Values"]
pretty_table(offer_values, header = h, row_labels = names)
#offer_values

┌───────────────────────────────────┬────────────┐
│                                   │     Values │
├───────────────────────────────────┼────────────┤
│                  TIER1 (24 insts) │   0.607084 │
│                  TIER2 (77 insts) │   0.486908 │
│                 TIER3 (198 insts) │   0.407543 │
│                 TIER4 (345 insts) │   0.163591 │
│                 TIER5 (621 insts) │ 0.00646005 │
│         Public Sector (226 insts) │   0.435835 │
│        Private Sector (335 insts) │   0.477125 │
│              Postdocs (801 insts) │   0.242724 │
│             Lecturers (614 insts) │   0.127996 │
│          Other Groups (674 insts) │   0.419238 │
│ Teaching Universities (814 insts) │   0.243448 │
└───────────────────────────────────┴────────────┘


In [29]:
path = files_path*"offer_values_table.tex"
open(path , "w") do f
        pretty_table(
            f,
            offer_values,
            header = h,
            row_labels = names,
            backend = Val(:latex)
            )
end

In [30]:
tier_values

5-element Vector{Any}:
 0.7491391725144698
 0.7485060197764076
 0.9728965591885285
 0.6783164494768414
 1.013347014167839

In [31]:
function likelihood_ratios(filtered_data, sinks, id_to_type_api, hiring_rates, 
        placement_rates, offer_values, tier_values, institution_id)
    """
        compute likelihood ratios by calculating the mutinomial probability of hires and placements using
        the ml poission rates for each of the tiers.  Normally, the tier to which they are assigned should
        have ratio 1, but with small numbers of placements or hires this breaks down
    
        In cases with no recorded hires, rates are set arbirarily to 1 for the tier, zero for everything else
        Not sure yet what happens when placements or hires are small, eg 1 or 2
    """
    
    institution = institution_lookup(id_to_type_api, institution_id)
    r = zeros(size(hiring_rates)[2])
    p = zeros(size(hiring_rates)[2])
    q = zeros(size(hiring_rates)[2])
    euclid = zeros(size(hiring_rates)[2])
    hiring = zeros(size(hiring_rates)[2])
    placing = zeros(size(hiring_rates)[2])
    t = institution["type"]
    name = institution["name"]
    #println(t, " ", name)
    
    # start with hiring
    a = hiring_outcomes(filtered_data, id_to_type_api, 
        size(hiring_rates)[2], parse(Int64, institution["institution_id"]))
    placements = placement_outcomes(filtered_data, sinks, id_to_type_api, 
        size(hiring_rates)[1], institution["institution_id"])
    if iszero(a)
        for k in 1:size(hiring_rates)[2]
            if k == t
                r[k] = 1
                break
            end
        end
        return Dict("name" => name, "id" => institution["institution_id"],
            "tier" => t, "ratios" => r , "hires" => a, "placements" => placements,
            "hiring_value" => 0, "placement_value" => transpose(offer_values)*placements)
    end 
    for i in 1:size(hiring_rates)[2]
        prod = 1
        for j in 1:length(a)
            prod = pdf(Poisson(hiring_rates[i,j]), a[j])*prod
        end
        p[i] = prod
    end
    for j in 1:size(hiring_rates)[2]
        hiring[j]=p[j]/p[t]
    end
    
    for i in 1:size(hiring_rates)[2]
        prod = 1
        for j in 1:length(placements)
            prod = pdf(Poisson(placement_rates[j,i]), placements[j])*prod
        end
        q[i] = prod
    end
    for j in 1:size(hiring_rates)[2]
        placing[j]=q[j]/q[t]
    end
    for j in 1:size(hiring_rates)[2]
        r[j]=(p[j]*q[j])/(p[t]*q[t])
    end
    for i in 1:size(hiring_rates)[2]
        euclid[i] = norm(vcat(a,placements)-vcat(hiring_rates[i,:],placement_rates[:,i]))
    end
    value_of_hires = transpose(tier_values)*a
    value_of_placements = transpose(offer_values)*placements

    return  Dict("name" => name, "id" => institution["institution_id"],
        "tier" => t, "ratios" => r, "hiring_ratios" => hiring,
        "placement_ratios" => placing, "hires" => a, "placements" => placements, "euclidian" => euclid,
        "hiring_value" => value_of_hires, "placement_value" => value_of_placements)
end

likelihood_ratios (generic function with 1 method)

In [32]:
# run various tests
a = likelihood_ratios(filtered_data, sinks, id_to_type_api, hiring_rates, placement_rates,
    offer_values, tier_values, 361
)
#a = hiring_outcomes(filtered_data, id_to_type_api, size(placement_rates)[2], 1765)
#a = placement_outcomes(filtered_data, sinks, id_to_type_api, size(placement_rates)[1], 32)
#id_to_type_api[9]["institution_id"]
#type_lookup(id_to_type_api,"350")

Dict{String, Any} with 11 entries:
  "tier"             => 1
  "placement_ratios" => [1.0, 1.13464e-22, 1.82432e-118, 2.67364e-274, 0.0]
  "hires"            => [47, 21, 13, 4, 1]
  "placement_value"  => 88.0355
  "name"             => "Cornell University"
  "euclidian"        => [51.9137, 54.6389, 81.5988, 90.8965, 92.8771]
  "id"               => "361"
  "hiring_ratios"    => [1.0, 1.52729e-6, 2.00428e-29, 6.91281e-76, 6.65857e-17…
  "ratios"           => [1.0, 1.73294e-28, 3.65645e-147, 0.0, 0.0]
  "placements"       => [30, 44, 37, 10, 2, 14, 29, 6, 4, 14, 16]
  "hiring_value"     => 67.3024

In [33]:


#save the calculations for all institutions
rep = []
for institution in id_to_type_api
    try
        s = likelihood_ratios(filtered_data, sinks, id_to_type_api, hiring_rates,
            placement_rates, offer_values, tier_values, institution["institution_id"])
        push!(rep, s)
    catch e
        rethrow(e)
    end
    
end
  

In [34]:
open(files_path*"likelihood_ratios.json", "w") do f
    write(f, JSON.json(rep))
end;

In [36]:
n = 0
m = 0
# set this to the tier you want to view
tier = 1
# set the next variable to zero to see all universities in the tier
# set it to 1 to see only those whose likelihood ratios don't support their tier assignment
anomalous = 0
for r in rep
    if r["tier"] == tier
        m += 1
        if maximum(r["ratios"]) > r["ratios"][r["tier"]]
            n +=1
            println(r["name"], " ", r["id"], " ", r["tier"])
            println("Anomalous ratio")
            for k in keys(r)
                println(k, " => ", r[k])
            end
            println("\n\n")
        else
            if anomalous == 1
                continue
            end
            println(r["name"], " ", r["id"], " ", r["tier"])
            for k in keys(r)
                println(k, " => ", r[k])
            end
            println("\n\n")
        end
    end
end
println("There were ", n, " anomalies")
println("The proportion ", n/m, " were anomalous") 

Boston University 29 1
tier => 1
placement_ratios => [1.0, 2.998126015659563e-31, 1.8689338454166986e-138, 0.0, 0.0]
hires => [31, 4, 10, 1, 2]
placement_value => 95.56421108904648
name => Boston University
euclidian => [63.862074687042025, 58.82627054520266, 81.55984217947696, 89.75541032160446, 91.40182031412115]
id => 29
hiring_ratios => [1.0, 25391.729616736924, 0.009479200650034545, 5.8994917558801865e-27, 3.1698932989263016e-79]
ratios => [1.0, 7.612760514653239e-27, 1.7715998922345528e-140, 0.0, 0.0]
placements => [25, 40, 46, 21, 1, 27, 39, 6, 1, 8, 14]
hiring_value => 38.651314496752



Columbia University 22 1
tier => 1
placement_ratios => [1.0, 4.8676748948197685e-108, 4.78285970871719e-283, 0.0, 0.0]
hires => [72, 24, 7, 2, 0]
placement_value => 149.57430470445138
name => Columbia University
euclidian => [16.94199663557988, 114.98457367916556, 140.3102542663963, 148.35135165232586, 149.93646964847457]
id => 22
hiring_ratios => [1.0, 5.717139906365539e-19, 3.16308293844843e-